### ISSUE TITLE
jq install fails

### ISSUE THREAD

**Issue by shortthefomo** [Xahau/jshooks-alpha#5]
running `./install`

results in "jq installed" failing.

git branch main

<img width="613" alt="Screenshot 2024-05-29 at 9 28 10 PM" src="https://github.com/Xahau/jshooks-alpha/assets/508629/96e84372-b479-4bbc-8c02-1aee3c0cb197">

**Comment by shortthefomo** [comment]
think I need to build this https://github.com/XRPL-Labs/jshooks-quickjs-runtime bit of a beast there.
<img width="1633" alt="Screenshot 2024-05-29 at 9 57 21 PM" src="https://github.com/Xahau/jshooks-alpha/assets/508629/d6a6d81c-c48a-4fbc-98c8-e1106304e4c6">

**Comment by WietseWind** [comment]
It doesn't install it for you, it checks if it is installed. Solution is to install jq.

Building QuickJS etc. etc. will be taken care of automatically, once you pass the installer requirements.

So install JQ and you'll be fine and the rest will be automatic :)

-- Homebrew has `jq` available, `brew install jq`
